listenerAddress: ":8080"
caminoNode: "https://kopernikus.camino.network"
networkID: 1002
database:
  dsn: "root:password@tcp(mysql:3306)/signavault?parseTime=true"
  type: "mysql"
txExpirationDays: 14
