// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/chain4travel/camino-signavault/service (interfaces: DepositOfferService)

// Package service is a generated GoMock package.
package service

import (
	reflect "reflect"

	dto "github.com/chain4travel/camino-signavault/dto"
	model "github.com/chain4travel/camino-signavault/model"
	gomock "github.com/golang/mock/gomock"
)

// MockDepositOfferService is a mock of DepositOfferService interface.
type MockDepositOfferService struct {
	ctrl     *gomock.Controller
	recorder *MockDepositOfferServiceMockRecorder
}

// MockDepositOfferServiceMockRecorder is the mock recorder for MockDepositOfferService.
type MockDepositOfferServiceMockRecorder struct {
	mock *MockDepositOfferService
}

// NewMockDepositOfferService creates a new mock instance.
func NewMockDepositOfferService(ctrl *gomock.Controller) *MockDepositOfferService {
	mock := &MockDepositOfferService{ctrl: ctrl}
	mock.recorder = &MockDepositOfferServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDepositOfferService) EXPECT() *MockDepositOfferServiceMockRecorder {
	return m.recorder
}

// AddSignatures mocks base method.
func (m *MockDepositOfferService) AddSignatures(arg0 *dto.AddSignatureArgs) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddSignatures", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddSignatures indicates an expected call of AddSignatures.
func (mr *MockDepositOfferServiceMockRecorder) AddSignatures(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddSignatures", reflect.TypeOf((*MockDepositOfferService)(nil).AddSignatures), arg0)
}

// GetSignatures mocks base method.
func (m *MockDepositOfferService) GetSignatures(arg0, arg1, arg2 string, arg3 bool) (*[]model.DepositOfferSig, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSignatures", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(*[]model.DepositOfferSig)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSignatures indicates an expected call of GetSignatures.
func (mr *MockDepositOfferServiceMockRecorder) GetSignatures(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSignatures", reflect.TypeOf((*MockDepositOfferService)(nil).GetSignatures), arg0, arg1, arg2, arg3)
}
