name: CI

on:
  pull_request:
    tags-ignore: ["*"]
    branches: [c4t, dev]
  push:
    branches: [c4t, dev]
  workflow_dispatch:

# Cancel ongoing workflow runs if a new one is started
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  go_version: '~1.20.12'

jobs:
  go_mod_tidy:
    name: Check state of go.mod and go.sum
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Update dependencies
        run: git submodule update --init
      - uses: actions/setup-go@v3
        with:
          go-version: ${{ env.go_version }}
      - name: Go Mod Tidy
        shell: bash
        run: go mod tidy
      - name: Check Clean Branch
        shell: bash
        run: .github/workflows/check-clean-branch.sh
  build_docker:
    name: Build Docker
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Submodules
        run: git submodule update --init --recursive
      - name: build docker image
        run: |
          docker build . -t signavault:temp
