name: build-docker-image

on:
  pull_request:
    branches:
        - c4t
        - dev

jobs:
  build_docker:    
    name: Build Docker
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Submodules
        run: git submodule update --init --recursive
      - name: build docker image
        run: |
          docker build . -t signavault:temp
