name: build-docker-image

on:
  pull_request:
    branches:
        - c4t
        - dev
  push:

jobs:
  build_docker:    
    name: Build Docker
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3


      - name: build docker image
        run: |
          docker build . -t signavault:temp
